version: '2.0'
services:
  registry:
    container_name: registry
    depends_on:
    - registry-backend
    image: registry:2
    volumes:
    - ./config.yml:/etc/docker/registry/config.yml
    ports:
    - 5000:5000
    - 5001:5001
  registry-backend:
    command: server /data
    container_name: registry-backend
    environment:
      MINIO_ACCESS_KEY: awsaccesskey
      MINIO_SECRET_KEY: awssecretkey
      MINIO_REGION: us-east-1
    image: minio/minio:latest
    volumes:
      - ./data:/data:z
    ports:
    - 9000:9000
  registry-frontend:
    container_name: registry-frontend
    depends_on:
    - registry
    environment:
      URL: http://127.0.0.1:5000
      DELETE_IMAGES: "true"
    image: joxit/docker-registry-ui:static
    ports:
    - 80:80
